// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwkwakufpcejmtupfemh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3a3dha3VmcGNlam10dXBmZW1oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NDI3ODgsImV4cCI6MjA2OTQxODc4OH0.mK8QmBhFlLFPG9SEzq6kKU0luaQJQ-m3g0nL94cVMNo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});